version: "3"

tasks:
  iwe:
    desc: Clone IWE and build bundled SKILL.md
    cmds:
      - rm -rf iwe
      - git clone https://github.com/iwe-org/iwe.git iwe
      - python3 ./build_iwe_skill.py
      - prettier --write ./iwe/SKILL.md
